name: Cypress test

on: [push]

jobs:
  cypress_test:
    runs-on: ubuntu-latest
    name: A Cypress test job
    steps:
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Clone repo
        run: git clone https://gitlab.com/richard.ng/cypress-tutorial.git
      - name: Serve app
        run: cd cypress-tutorial && npx serve &
      - name: Run test
        run: cd cypress-tutorial/e2e && npm install && npm run cypress:run
