name: Cypress test

on: [push]

jobs:
  cypress_test:
    runs-on: ubuntu-latest
    name: A Cypress test job
    steps:
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Clone repo
        run: |
          git clone https://gitlab.com/richard.ng/cypress-tutorial.git
          cd cypress-tutorial
      - name: Serve app
        run: npx serve
