name: Test pull private repo

on: [push]

jobs:
  private_repo:
    runs-on: ubuntu-latest
    name: Test pull private repo
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
        with:
          repository: richardkng/richardkng.github.io
