name: Test pull private repo

on: [push]

jobs:
  private_repo:
    runs-on: ubuntu-latest
    name: Test pull private repo
    steps:
      - name: Clone repo
        run: git clone https://github.com/richardkng/private-gha.git
